[package]
name = "yolox_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace", "std"] }
image = "0.24.7"
tract-onnx = "0.20.21"
